version: '3.9'

services:
  mongodb:
    image: mongo:8
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: database
    volumes:
      - mongodata:/data/db
    networks:
      - backend-service
  
  microsoft-graph-interface-app:
    build: .
    ports:
      - 8080:8080
    restart: always
    networks:
      - backend-service
    depends_on:
      - mongodb

networks:
  backend-service:
    driver: bridge

volumes:
  mongodata:
    driver: local